package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseResource<M extends BaseResource<M>> extends Model<M> implements IBean {

    public java.lang.Integer getResourceId() {
        return get("resource_id");
    }

    public void setResourceId(java.lang.Integer resourceId) {
        set("resource_id", resourceId);
    }

    public java.lang.String getClientSysId() {
        return get("client_sys_id");
    }

    public void setClientSysId(java.lang.String clientSysId) {
        set("client_sys_id", clientSysId);
    }

    public java.lang.String getName() {
        return get("name");
    }

    public void setName(java.lang.String name) {
        set("name", name);
    }

    public java.lang.String getType() {
        return get("type");
    }

    public void setType(java.lang.String type) {
        set("type", type);
    }

    public java.lang.String getUrl() {
        return get("url");
    }

    public void setUrl(java.lang.String url) {
        set("url", url);
    }

    public java.lang.String getImgPath() {
        return get("img_path");
    }

    public void setImgPath(java.lang.String imgPath) {
        set("img_path", imgPath);
    }

    public java.lang.Integer getParentId() {
        return get("parent_id");
    }

    public void setParentId(java.lang.Integer parentId) {
        set("parent_id", parentId);
    }

    public java.lang.String getParentIds() {
        return get("parent_ids");
    }

    public void setParentIds(java.lang.String parentIds) {
        set("parent_ids", parentIds);
    }

    public java.lang.String getPermission() {
        return get("permission");
    }

    public void setPermission(java.lang.String permission) {
        set("permission", permission);
    }

    public java.lang.String getAvailable() {
        return get("available");
    }

    public void setAvailable(java.lang.String available) {
        set("available", available);
    }

}
