package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRole<M extends BaseRole<M>> extends Model<M> implements IBean {

    public java.lang.Integer getRoleId() {
        return get("role_id");
    }

    public void setRoleId(java.lang.Integer roleId) {
        set("role_id", roleId);
    }

    public java.lang.String getClientSysId() {
        return get("client_sys_id");
    }

    public void setClientSysId(java.lang.String clientSysId) {
        set("client_sys_id", clientSysId);
    }

    public java.lang.String getRoleName() {
        return get("role_name");
    }

    public void setRoleName(java.lang.String roleName) {
        set("role_name", roleName);
    }

    public java.lang.String getDescription() {
        return get("description");
    }

    public void setDescription(java.lang.String description) {
        set("description", description);
    }

    public java.lang.String getAvailable() {
        return get("available");
    }

    public void setAvailable(java.lang.String available) {
        set("available", available);
    }

    public java.lang.String getRegId() {
        return get("reg_id");
    }

    public void setRegId(java.lang.String regId) {
        set("reg_id", regId);
    }

}
