package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRolePermission<M extends BaseRolePermission<M>> extends Model<M> implements IBean {

    public java.lang.Integer getId() {
        return get("id");
    }

    public void setId(java.lang.Integer id) {
        set("id", id);
    }

    public java.lang.Integer getRoleId() {
        return get("role_id");
    }

    public void setRoleId(java.lang.Integer roleId) {
        set("role_id", roleId);
    }

    public java.lang.Integer getPermissionId() {
        return get("permission_id");
    }

    public void setPermissionId(java.lang.Integer permissionId) {
        set("permission_id", permissionId);
    }

}
