package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePermission<M extends BasePermission<M>> extends Model<M> implements IBean {

    public java.lang.Integer getId() {
        return get("id");
    }

    public void setId(java.lang.Integer id) {
        set("id", id);
    }

    public java.lang.String getName() {
        return get("name");
    }

    public void setName(java.lang.String name) {
        set("name", name);
    }

    public java.lang.Integer getType() {
        return get("type");
    }

    public void setType(java.lang.Integer type) {
        set("type", type);
    }

    public java.lang.String getUrl() {
        return get("url");
    }

    public void setUrl(java.lang.String url) {
        set("url", url);
    }

    public java.lang.String getIconCls() {
        return get("icon_cls");
    }

    public void setIconCls(java.lang.String iconCls) {
        set("icon_cls", iconCls);
    }

    public java.lang.Integer getParentId() {
        return get("parent_id");
    }

    public void setParentId(java.lang.Integer parentId) {
        set("parent_id", parentId);
    }

    public java.lang.String getParentIds() {
        return get("parent_ids");
    }

    public void setParentIds(java.lang.String parentIds) {
        set("parent_ids", parentIds);
    }

    public java.lang.String getPermission() {
        return get("permission");
    }

    public void setPermission(java.lang.String permission) {
        set("permission", permission);
    }

    public java.lang.Integer getStatus() {
        return get("status");
    }

    public void setStatus(java.lang.Integer status) {
        set("status", status);
    }

    public java.util.Date getCreateTime() {
        return get("create_time");
    }

    public void setCreateTime(java.util.Date createTime) {
        set("create_time", createTime);
    }

    public java.util.Date getUpdateTime() {
        return get("update_time");
    }

    public void setUpdateTime(java.util.Date updateTime) {
        set("update_time", updateTime);
    }

    public java.lang.String getDesc() {
        return get("desc");
    }

    public void setDesc(java.lang.String desc) {
        set("desc", desc);
    }

}
