package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

    public java.lang.Integer getUserId() {
        return get("user_id");
    }

    public void setUserId(java.lang.Integer userId) {
        set("user_id", userId);
    }

    public java.lang.String getClientSysId() {
        return get("client_sys_id");
    }

    public void setClientSysId(java.lang.String clientSysId) {
        set("client_sys_id", clientSysId);
    }

    public java.lang.String getRegId() {
        return get("reg_id");
    }

    public void setRegId(java.lang.String regId) {
        set("reg_id", regId);
    }

    public java.lang.String getUsername() {
        return get("username");
    }

    public void setUsername(java.lang.String username) {
        set("username", username);
    }

    public java.lang.String getPassword() {
        return get("password");
    }

    public void setPassword(java.lang.String password) {
        set("password", password);
    }

    public java.lang.String getName() {
        return get("name");
    }

    public void setName(java.lang.String name) {
        set("name", name);
    }

    public java.lang.String getSalt() {
        return get("salt");
    }

    public void setSalt(java.lang.String salt) {
        set("salt", salt);
    }

    public java.lang.String getLocked() {
        return get("locked");
    }

    public void setLocked(java.lang.String locked) {
        set("locked", locked);
    }

    public java.lang.String getPwdChangedate() {
        return get("pwd_changedate");
    }

    public void setPwdChangedate(java.lang.String pwdChangedate) {
        set("pwd_changedate", pwdChangedate);
    }

    public java.lang.String getLoginLimitDate() {
        return get("login_limit_date");
    }

    public void setLoginLimitDate(java.lang.String loginLimitDate) {
        set("login_limit_date", loginLimitDate);
    }

    public java.lang.String getLoginLimitCountRemain() {
        return get("login_limit_count_remain");
    }

    public void setLoginLimitCountRemain(java.lang.String loginLimitCountRemain) {
        set("login_limit_count_remain", loginLimitCountRemain);
    }

    public java.lang.String getLastLoginTime() {
        return get("last_login_time");
    }

    public void setLastLoginTime(java.lang.String lastLoginTime) {
        set("last_login_time", lastLoginTime);
    }

    public java.lang.String getEmail() {
        return get("email");
    }

    public void setEmail(java.lang.String email) {
        set("email", email);
    }

    public java.lang.String getMobile() {
        return get("mobile");
    }

    public void setMobile(java.lang.String mobile) {
        set("mobile", mobile);
    }

}
