package com.demo.common.model;

import com.demo.common.model.base.BasePermission;
import com.jfinal.plugin.activerecord.Page;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Permission extends BasePermission<Permission> {
    public static final Permission dao = new Permission();

    public Page<Permission> paginate(int page, int rows) {
        return paginate(page, rows, "SELECT DISTINCT a.*", "FROM tbl_permission a ORDER BY CONCAT(a.`parent_ids`,a.`id`) ASC");
    }

    public List<Permission> findAll() {
        return Permission.dao.find("SELECT DISTINCT a.* FROM tbl_permission a ORDER BY CONCAT(a.`parent_ids`,a.`id`) ASC");
    }
}
