package com.demo.common.model;

import com.demo.common.model.base.BaseRole;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Role extends BaseRole<Role> {
    public static final Role dao = new Role();

    public Page<Role> paginate(int page, int rows) {
        return paginate(page, rows, "select *", "from tbl_role order by id asc");
    }
}
