package com.demo.common.model;

import com.demo.common.model.base.BaseTag;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Tag extends BaseTag<Tag> {
    public static final Tag dao = new Tag();
}
