package com.demo.common.model;

import com.demo.common.model.base.BaseUser;
import com.demo.common.page.Result;
import com.jfinal.plugin.activerecord.Page;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
    public static final User dao = new User();

    public Page<User> paginate(int pageNumber, int pageSize) {
        return paginate(pageNumber, pageSize, "select *", "from tbl_user order by id asc");
    }

    public List<User> list() {
        return User.dao.find("select * from tbl_user");
    }

    public Result add(User user) {
        return null;
    }
}
